### ISSUE TITLE
Stop broadcasting of user addresses

### ISSUE THREAD

**Issue by biocrypto730** [BadgerWallet/badger#18] opened 2019-03-23 20:53 UTC
I feel very strongly about this and I need this to be fixed before developing a dApp for BCH

https://github.com/MetaMask/metamask-extension/issues/6325

Can BadgerWallet do what MetaMask cant? Enable private mode by default, but especially just remove the cash addresses from message broadcasts

**Comment by wbt** [comment] 2019-06-21 19:04
Is this just a duplicate of [#6325](https://github.com/MetaMask/metamask-extension/issues/6325)?

**Comment by biocrypto730** [comment] 2019-10-18 16:17
Has this been addressed? I don't get this issue when running it in the browser anymore.

**Closed as completed** 2019-10-18 16:19 UTC

**Comment by wbt** [comment] 2019-10-18 18:21
See the linked original.  Please note that opening duplicate issues takes developers' time away from being able to actually address the issues.  It also violates the community norm, especially when it's intentional, which makes folks even less likely to invest time addressing the issue you've raised, compared to others.

Finally, "Can X do what *this open source project* cannot" is not a motivating question for open source developers who are generally trying to provide useful functionality rather than a competitive business product.  The same information might be better framed as "X does this *with specifics of how*" and if the other project is open source, ideally a link to the file(s)/line(s)/pull request(s) where it's done and note about the other project's license, to facilitate faster implementation of the same ideas in a new project.

**Comment by biocrypto730** [comment] 2019-10-18 19:07
I'll take your advice in your second point, but for the first one:

1. You said "see linked original" but their arguments were like wrong... MetaMask ended up changing their code to patch the broadcast issue by the end of that month. They didn't openly admit their mistake, but about a dozen crypto sites picked up the story. If you read the issue again you'll see nothing they said really made any technical sense. I have a bit of a backstabbed history with Ethereum in general, so I was really accusatory, and I could see why it would have been hard to read past that.

2. This repo doesn't say "Forked from metamask" on it. So there's no reason for me to assume that bugs patched in one branch would be patched in the second. 


What i should have done in that issue was file a pull request. I'm not sure it would have taken me that long to patch the bug myself. I was angry at MetaMask for business reasons but I didn't need to take it out on the open-source devs.

**Comment by wbt** [comment] 2019-10-18 19:50
Whoops, my bad.  I erroneously thought this issue we were discussing on was in MetaMask.  It isn't.    
Now I kind of wonder how I wound up in a BadgerWallet Issue, having not interacted with the software itself.    
You are correct in opening the same issue with appropriate cross references in different repositories that may have the same issue in the code, where changes in one are not necessarily expected to flow to the other.

**Comment by biocrypto730** [comment] 2019-10-18 20:21
In the original metamask issue, a link comes up that says "... referenced this issue in #18". When you follow that link it takes you outside that repository and into here.

Usually the "referenced this issues"  stay inside the same repository most of the time they come up. It just so happens that these two codebases had the same issue, possibly because they are pretty much the same
